import type { NewCard } from '../types/vocab.js';

export const DEFAULT_DECK_NAME = 'Getting Started';

export function buildSampleDeck(importId: string): NewCard[] {
  const now = Date.now();
  const cards: NewCard[] = [
    {
      front: 'bonjour',
      back: 'hello (informal)',
      context: 'Bonjour ! Comment ça va ?',
      tags: ['greeting'],
      deck: DEFAULT_DECK_NAME,
      createdAt: now,
      importId,
      interval: 0,
      repetitions: 0,
      easeFactor: 2.5,
      dueAt: now,
    },
    {
      front: 'merci',
      back: 'thank you',
      context: 'Merci beaucoup pour votre aide.',
      tags: ['greeting'],
      deck: DEFAULT_DECK_NAME,
      createdAt: now,
      importId,
      interval: 0,
      repetitions: 0,
      easeFactor: 2.5,
      dueAt: now,
    },
    {
      front: 'serendipity',
      back: 'a pleasant surprise',
      context: 'Finding that café was pure serendipity.',
      tags: ['noun'],
      deck: DEFAULT_DECK_NAME,
      createdAt: now,
      importId,
      interval: 0,
      repetitions: 0,
      easeFactor: 2.5,
      dueAt: now,
    },
    {
      front: 'ephemeral',
      back: 'lasting for a very short time',
      context: 'Fashion is ephemeral; trends fade quickly.',
      tags: ['adjective'],
      deck: DEFAULT_DECK_NAME,
      createdAt: now,
      importId,
      interval: 0,
      repetitions: 0,
      easeFactor: 2.5,
      dueAt: now,
    },
    {
      front: 'resilient',
      back: 'able to recover quickly from difficulties',
      context: 'Children are often more resilient than adults.',
      tags: ['adjective'],
      deck: DEFAULT_DECK_NAME,
      createdAt: now,
      importId,
      interval: 0,
      repetitions: 0,
      easeFactor: 2.5,
      dueAt: now,
    },
    {
      front: 'nuance',
      back: 'a subtle difference in meaning or expression',
      context: 'Understanding the nuance takes years of practice.',
      tags: ['noun'],
      deck: DEFAULT_DECK_NAME,
      createdAt: now,
      importId,
      interval: 0,
      repetitions: 0,
      easeFactor: 2.5,
      dueAt: now,
    },
    {
      front: 'apropos',
      back: 'with regard to; opportune',
      context: 'Your remark was apropos of our discussion.',
      tags: ['adjective'],
      deck: DEFAULT_DECK_NAME,
      createdAt: now,
      importId,
      interval: 0,
      repetitions: 0,
      easeFactor: 2.5,
      dueAt: now,
    },
    {
      front: 'luminous',
      back: 'full of or shedding light; bright',
      context: 'The luminous dial glowed in the dark.',
      tags: ['adjective'],
      deck: DEFAULT_DECK_NAME,
      createdAt: now,
      importId,
      interval: 0,
      repetitions: 0,
      easeFactor: 2.5,
      dueAt: now,
    },
    {
      front: 'cogent',
      back: 'clear, logical, and convincing',
      context: 'She presented a cogent argument.',
      tags: ['adjective'],
      deck: DEFAULT_DECK_NAME,
      createdAt: now,
      importId,
      interval: 0,
      repetitions: 0,
      easeFactor: 2.5,
      dueAt: now,
    },
    {
      front: 'ubiquitous',
      back: 'present, appearing, or found everywhere',
      context: 'Smartphones have become ubiquitous.',
      tags: ['adjective'],
      deck: DEFAULT_DECK_NAME,
      createdAt: now,
      importId,
      interval: 0,
      repetitions: 0,
      easeFactor: 2.5,
      dueAt: now,
    },
  ];
  return cards;
}
